export const GEAR_NAMES = {
  'i7061': 'Elite Gryphon Helmet Piece',
  'i7062': 'Elite Gryphon Armor Piece',
  'i7063': 'Elite Gryphon Ring Piece',
  'i7064': 'Elite Gryphon Saddle Piece',
  'i7065': 'Elite Gryphon Steel Talons Piece',
  'i7066': 'Elite Hellhound Helmet Piece',
  'i7067': 'Elite Hellhound Armor Piece',
  'i7068': 'Elite Hellhound Ring Piece',
  'i7069': 'Elite Hellhound Saddle Piece',
  'i7070': 'Elite Hellhound Whip Piece',
  'i7071': 'Elite Raven Helmet Piece',
  'i7072': 'Elite Raven Armor Piece',
  'i7073': 'Elite Raven Ring Piece',
  'i7074': 'Elite Raven Saddle Piece',
  'i7075': 'Elite Raven Steel Talons Piece',
  'i7076': 'Elite Halia Helmet Piece',
  'i7077': 'Elite Halia Armor Piece',
  'i7078': 'Elite Halia Ring Piece',
  'i7079': 'Elite Halia Breastplate Piece',
  'i7080': 'Elite Halia Legwear Piece',
  'i7081': 'Elite Voidrake Helmet Piece',
  'i7082': 'Elite Voidrake Armor Piece',
  'i7083': 'Elite Voidrake Ring Piece',
  'i7084': 'Elite Voidrake Saddle Piece',
  'i7085': 'Elite Voidrake Steel Talons Piece',
  'i7086': 'Elite Helhest Helmet Piece',
  'i7087': 'Elite Helhest Armor Piece',
  'i7088': 'Elite Helhest Ring Piece',
  'i7089': 'Elite Helhest Breastplate Piece',
  'i7090': 'Elite Helhest Legwear Piece',
};
